### ISSUE TITLE
detect-trust-cert not working

### ISSUE THREAD

**Issue by elgohr** [synopsys-sig/detect-action#23]
Leaving it empty, setting it explicitly to 'TRUE' or 'FALSE' - all results in 
```
Creating Black Duck Policy Check...
Black Duck Policy Check created
detect-version: 7.9.0
output-path-override: 
scan-mode: RAPID
Checking that you have at least one enabled policy...
Initiating authentication request to Black Duck...
Error: Failed due to an unhandled error: 'Error: self signed certificate in certificate chain'
Black Duck Policy Check updated
```

**Comment by elgohr** [comment]
`NODE_TLS_REJECT_UNAUTHORIZED: 0` needs to be provided as an environment variable, to get around this.
Would have expected that this would be set when using `detect-trust-cert`

**Comment by jcroall** [comment]
This is a great catch! What's happening is the interaction of detect and the NodeJS runtime. @shubham0572 we should file a Jira ticket on this.
