### ISSUE TITLE
Missing options to set detect scan arguments

### ISSUE THREAD

**Issue by DavidGailmannVW** [synopsys-sig/detect-action#24]
It is not possible to set all detect scan arguments like:

        #       --detect.project.version.name
        #       --detect.project.name
        #       --detect.included.detector.types
        #       --logging.level.detect
        #       --detect.source.path

and so on.

Kindly regards

**Comment by jcroall** [comment]
Hi @DavidGailmannVW these can be set by passing environment variables like:

- DETECT_PROJECT_VERSION_NAME
- DETECT_PROJECT_NAME
- etc.

This is described in "Additional Detect Properties" in the README. This is a standard way to use Detect. We opted to only pass things by environment variable to avoid dealing with escaping and cross-platform issues going from the NodeJS runtime to the command line.

**Comment by DavidGailmannVW** [comment]
Perfect ist works. Thank you very much :)
